Repository vishal-lokare/AutoJoomer, pull requests merged in 2021-10, with the labels that each got.

#36 Changed screenshots
  README.md
  logger.js
  screenshots/autojoomer.jpg
  screenshots/devmode.jpg
  screenshots/ziporclone.jpg
Labels: hacktoberfest-accepted

#38 slider
  popup.html
Labels: hacktoberfest-accepted

#40 Fixed a bug
  popup.html
Labels: bug, hacktoberfest-accepted

#41 Update with main
  README.md
  logger.js
  popup.html
  screenshots/autojoomer.jpg
  screenshots/devmode.jpg
  screenshots/ziporclone.jpg
Labels: hacktoberfest-accepted

#48 Update to readme.md
  README.md
Labels: hacktoberfest-accepted

#55 new class_time property in backup.json
  backup.json
Labels: hacktoberfest-accepted

#57 Fixed backup.json
  backup.json
Labels: hacktoberfest-accepted

#58 Class_time feature added in script.js
  script.js
Labels: hacktoberfest-accepted

#59 Fixed script.js and added a few comments
  script.js
Labels: hacktoberfest-accepted

#60 Update with main
  README.md
  backup.json
  script.js
Labels: hacktoberfest-accepted

#62 Features added
  popup.html
  popup.js
  script.js
Labels: hacktoberfest2021

#65 fixed silly h,m array error
  manifest.json
  script.js
Labels: hacktoberfest-accepted

#68 github link added
  manifest.json
  popup.js
  script.js
Labels: hacktoberfest-accepted

#69 window.confirm for 'new update' dialog box
  manifest.json
  popup.js
  script.js
Labels: hacktoberfest-accepted

#70 fixed a silly parsing bug
  manifest.json
  script.js
Labels: hacktoberfest-accepted

#71 Parsing and new in this update
  manifest.json
  popup.js
  script.js
  version_updates.json
Labels: hacktoberfest-accepted
